### ISSUE TITLE
*** PUSHING TOWARDS NEXT VERSION ***

### ISSUE THREAD

**Issue by ajthinking** [pipe-dream/laravel-create#58]
# Next version 🚀 
This thread is for all contributors, want-to-be-contributors and also in specific response to @septIO and @adhikasp to discuss how to get to the next version of the pipe dream platform. 

## Roadmap
Preliminary time frames (open for discussion):

| version | info  | when  |
|---|---|---|
| alpha | this repo at its current state | Released June 2019 |
| beta 1 | implementation of the new platform including laravel support | September 2019  |
| beta 2 | implementation of an additional 1-3 languages/frameworks | October 2019  |
| V1 | more advanced features | 2020 |

## Baseline / scope
We need to setup a scope all the way to `beta 2` (with `V1` somewhat in mind). How can we do that? The [Trello](https://trello.com/b/R11mhfdy/pipe-dream) board could potentially act as a guide using the columns:
* IDEAS = things to be decided on
* QUEUED FOR BETA = minimum scope
* POSTPONED TO V1 = cool ideas to keep for later

But I'm sure there are better ways? Illustrations/wireframes? Feature list in google sheets? Suggestions needed!

## Rewrite suggestions
> make core/other module a proper ES6 module with webpack build, so we don't need to write workaround for things like jest and file loader.

This sounds good, I'm not that experienced with how to export the packages in a modular way, Im sure there are a lot of room for improvement from the initial package setup. 👍 

> ... Core rewrite? I’ve read through it, and i see alot of optimization options, and some class/file names doesn’t always make sense as to what they do. I would also like to abstract each component further (as discussed on the [GitHub issue](https://github.com/pipe-dream/core/issues/2)). What are your thoughts of writing the core in TypeScript to ensure typesafety, and use some of the better parts of TypeScript such as private properties/methods, interfaces, traits etc.

I think we should pursue high quality, and all of this sounds like good ideas! 👍 

## Collaboration channels

| resource | purpose |
|---|---|
| [Trello](https://trello.com/b/R11mhfdy/pipe-dream) | Overview work planning |
| [Issues in this or other repos](https://github.com/pipe-dream/laravel/issues) | Detailed issue/dev discussion, since better than trello (?) |
| [pipedream docs](https://github.com/pipe-dream/docs) | User/Developer docs + platform overview |

Pipe Dream is in a way abstractions of abstractions and I have a hard time wrapping my head around it all. I usually do a lot of sketches in a physical notepad, but thats not good enough. Maybe we also need some kind of vector modeling tool to explain ideas and make them commitable for documentation. Any ideas? I tried [draw.io](https://drive.google.com/file/d/1CmZvJY_6q6iZJ96RdEbg_W9Gw0W_G42B/view?usp=sharing) which is cool but maybe not that smart for application development?

<hr>

**Comment by elbojoloco** [comment]
Hey!

One question, what do you mean with "beta 1: implementation of the new platform including laravel support" 
Isn't laravel already supported?

And another question, if I'd like to contribute to what is generate by the `blocks` (example: `___RELATIONSHIP_METHODS_BLOCK___`) where would I need to look for what is output by that?

**Comment by septIO** [comment]
@elbojoloco Beta 1 will see a complete rewrite of the pipe-dream core, and should come along with _mor or less_ complete laravel support. 

Regarding question about `blocks`, if you want to make a new `block`, you need to add it to the `template` (Can be found in`[vendor]/pipe-dream/laravel/src/templates/`). If you want to extend the generated code from an already declared `block` (Let's take `___RELATIONSHIP_METHODS_BLOCK___` as of your example) you'll have to edit the fileFactory for that template (Let's say `Model`). This factory can be found in `[vendor]/pipe-dream/laravel/src/resources/js/fileFactories/pipes/ModelPipe.js` (for models, see the directory for a full list of all available pipes).
The specific code you're looking for in your example is at ModelPipe.js:15, that calls a method that's located on line 80. Take a look there.

**Comment by damms005** [comment]
Have option to generated resource controllers (rather than plain controllers), i.e. `php artisan make:controller -r ...`

**Comment by ajthinking** [comment]
@damms005 - good idea! Adding it to the feature list. Thanks!

**Comment by gurinder-xyrintech** [comment]
plz add $table->softDeletes() method
and plz add option to set default values in migration
