### ISSUE TITLE
Default user and reset password migration removed

### ISSUE THREAD

**Issue by more-yogesh** [pipe-dream/laravel-create#62]
I installed the pipe dream in an **existing project.** 
But **I did not use the +USER SYSTEM** option just created a single model and after building the module, my user and password_reset migration removed.

Thanks for the package :)

**Comment by Taalaybek** [comment]
#meToo Can I undo this?

**Comment by gurinder-xyrintech** [comment]
use git after created models restore your existing files

**Comment by ajthinking** [comment]
Hey, thanks for the report. Finally, this issue has been solved in `v0.1.7` where we simplified the file states. The original migrations will now be kept - unless the user specifies a new User model or password_resets colliding with the default ones. Like @gurinder-xyrintech says, use git to confirm after building 👍
