### ISSUE TITLE
failed to open stream: Permission denied

### ISSUE THREAD

**Issue by burmkiller** [pipe-dream/laravel-create#63]
After I cloned my github repo into my ubuntu server, it kept giving me this error for some reason, I know it's a permission error but I cannot figure out where exactly is the file that lacks the right permissions, anyone with a solution?

copy(/var/www/html/emailplat/emailplat/public/vendor/pipe-dream/laravel/data/.gitignore): failed to open stream: Permission denied

**Comment by ajthinking** [comment]
@burmkiller sorry for the slow response, did you find a solution? 
The plan was to have every asset published by pipe-dream ignored but that might not be working as intended...
