### ISSUE TITLE
Overriding the templates folder

### ISSUE THREAD

**Issue by lemonlover** [pipe-dream/laravel-create#64]
Hi. Great package! 

Can you explain how i can override templates folder to use my sample controllers?

Thank you!

**Comment by MflJoe** [comment]
php artisan vendor:publish --tag=templates will publish the default templates to a folder in your storage directory, where you can change & save them.

**Comment by ajthinking** [comment]
Thanks for the question and answer @lemonlover & @MflJoe !

Since we upgraded the platform in release `v0.1.0` this solution unfortunately will not work anymore. But it do work in `^0.0.75`.

There will soon be a feature fixing this and similar use case available at https://pipedream.ai.
