### ISSUE TITLE
GUI should keep object model sketch when development server or browser tab is closed.

### ISSUE THREAD

**Issue by aonurdemir** [pipe-dream/laravel-create#67]
After closing the dev server or sketch window, incomplete sketch text is lost. It can be stored in browser storage in order to be able to continue where it is left off.

**Comment by ajthinking** [comment]
Thanks for the report! There is a start to implementation to this problem - open console and you can see a "Save not implemented yet" message.

**Comment by ajthinking** [comment]
Fixed in `v0.1.9`
