### ISSUE TITLE
Ability to create GraphQL type system

### ISSUE THREAD

**Issue by calvinchiulele** [pipe-dream/laravel-create#68]
Hi! Will laravel-create in any future versions support the ability to create a GraphQL type system?

**Comment by septIO** [comment]
@calvinchiulele If you mean something like `name: string`, then yes. We're working towards making a simplistic syntax for type definitions. It will only work with scalar type though. Once the next build is stable I'll take a look at implementing the syntax. Take a look at this discussion: https://github.com/pipe-dream/core/issues/6#issuecomment-510885144

If you ask about having
```
type Car {
    name: String!,
    manufacturer: [Manufacturer!]!
}
```
Then no. We want the sketch to as simple as possible.

**Comment by calvinchiulele** [comment]
Ohh! I wasn't referring about scalar type system. But it's ok, we'll do it manually.
Thank you!

**Comment by ajthinking** [comment]
Possibly do a custom file factory overriding how the sketch is interpreted??
