### ISSUE TITLE
Frontend?

### ISSUE THREAD

**Issue by dgleba** [pipe-dream/laravel-create#73]
The pipedream.ai website says:

Create backend and frontend code in minutes using a simple sketch syntax. Get best practice predictions from 300 000 github repositories.

I am looking for how to create frontend code with pipedream.

Can someone help me find it?

**Comment by ajthinking** [comment]
Sorry @dgleba, unfortunately there are no working frontend file-factories at this time. Fixed the wordings on the site! Thanks!
