### ISSUE TITLE
API path not working in laravel 6.6.2

### ISSUE THREAD

**Issue by Daniyal-Javani** [pipe-dream/laravel-create#75]
Hey
I love this package, you made my life easier!

While the api path is `app/Http/Controllers/API` like this:
![image](https://user-images.githubusercontent.com/8044163/70258633-cb86bd00-17a1-11ea-88c1-bb84027afe58.png)
Still they are in the controllers directory:
![image](https://user-images.githubusercontent.com/8044163/70258730-f7a23e00-17a1-11ea-93f0-8a1dec0f2776.png)

Not sure if it's my mistake or it's a bug.

**Comment by ajthinking** [comment]
Hi Daniyal, thanks for the encouragement! This bug should be fixed in `v0.1.4` 👍
