### ISSUE TITLE
Broken in Laravel 7

### ISSUE THREAD

**Issue by mobiusmedia** [pipe-dream/laravel-create#83]
In a fresh install of Laravel 7 you get a white screen due to a failure to load vendor JS & CSS resources

**Comment by septIO** [comment]
@mobiusmedia Thank you for testing it out in Laravel 7.
Yesterday we pushed a new version that splits this package up into smaller repositories for simplicity sake. The documentation for this change has yet to be announced, and I'm sorry you're having issues.

What you need to do is install the file factory by running `npm install laravel-file-factory` and then use `php artisan pipedream:install`. This should fix your issue

**Comment by juliofagundes** [comment]
> @mobiusmedia Thank you for testing it out in Laravel 7.
> Yesterday we pushed a new version that splits this package up into smaller repositories for simplicity sake. The documentation for this change has yet to be announced, and I'm sorry you're having issues.
> 
> What you need to do is install the file factory by running `npm install laravel-file-factory` and then use `php artisan pipedream:build`. This should fix your issue

`npm install @pipe-dream/laravel-file-factory`
